stages:
  - test

yamllint:
  image: python:3
  stage: test 
  before_script:
    - pip install yamllint
  script:
    - yamllint .

rulecheck:
  image: ruby:3-alpine
  before_script:
    - gem install psych justify yaml fileutils
    - ./scripts/autoformat.rb

