stages:
  - test

yamllint:
  image: python:2.7
  stage: test 
  before_script:
    - pip install yamllint
  script:
    - yamllint .

rulecheck:
  stage: test 
  image: ruby:3-alpine
  before_script:
    - apk add --no-cache yaml-dev alpine-sdk
    - gem install psych yaml fileutils
  script:
    - ./scripts/autoformat.rb

