# yamllint disable
# License: MIT (c) GitLab Inc.
# source (original): https://github.com/ajinabraham/njsscan/blob/master/njsscan/rules/semantic_grep/electronjs/security_electron.yaml
# hash: e7a0a61
# yamllint enable
---
rules:
- id: "javascript/electronjs/rule-electron_disable_websecurity"
  patterns:
  - pattern-either:
    - pattern: 'new BrowserWindow({webPreferences: {webSecurity: false}})

        '
    - pattern: 'var $X = {webPreferences: {webSecurity: false}};

        '
  message: |
    Disabling webSecurity will disable the same-origin policy and allows the execution of insecure code from any domain.
  languages:
  - "javascript"
  severity: "ERROR"
  metadata:
    owasp: "A6:2017-Security Misconfiguration"
    cwe: "CWE-346: Origin Validation Error"
